#ifndef constants
#define constants

#define BLOCK_SIZE_BITS 64
#define HALF_BLOCK_SIZE_BITS 32
#define RIGHT_HALF_BLOCK_ON 0xFFFFFFFF
#define LEFT_HALF_BLOCK_ON 0xFFFFFFFF00000000
#define KEY_SIZE_BITS 56
#define SUBKEY_SIZE_BITS 48
#define HALF_KEY_SIZE_BITS 28
#define RIGHT_HALF_KEY_ON 0xFFFFFFF
#define S_BOXES_COUNT 8
#define S_BOXES_ROWS 4
#define S_BOXES_COLS 16

#define BLOCK_SIZE_BYTES 8
#define INT_32_BITS 32
#define INT_4_BYTES 4

//define errors:
#define ERROR_NONE 0
#define ERROR_COULD_NOT_OPEN_FILE 1
#define ERROR_COULD_NOT_READ_PREFIX 2
#define ERROR_COULD_NOT_REMOVE_PADDING 3

#endif