#ifndef constants
#define constans

#define BLOCK_SIZE_BITS 64
#define HALF_BLOCK_SIZE_BITS 32
#define RIGHT_HALF_BLOCK_ON 0xFFFFFFFF
#define LEFT_HALF_BLOCK_ON 0xFFFFFFFF00000000
#define KEY_SIZE_BITS 56
#define SUBKEY_SIZE_BITS 48
#define HALF_KEY_SIZE_BITS 28
#define RIGHT_HALF_KEY_ON 0xFFFFFFF
#define BLOCK_SIZE_BYTES 8
#define INT_32_BITS 32
#define INT_4_BYTES 4

#endif